#!/usr/bin/env python3
"""Bake assets/atlas.png for the graphical (Macroquad) frontend.

Sources: Kenney's CC0 "Roguelike/RPG pack" and "Roguelike Characters"
(https://kenney.nl), both 16x16 tiles with a 1px margin. This script picks the
handful of sprites the game needs, composes/tints the characters, adds a few
hand-pixeled critters, and packs everything into one margin-free atlas whose
cell order matches the constants in src/gfx/atlas.rs.

Usage: python3 tools/bake_atlas.py <roguelikeSheet_transparent.png> <roguelikeChar_transparent.png>
"""

import sys
from pathlib import Path

from PIL import Image

TILE = 16
COLS = 16  # atlas cells per row

NA_DIR = Path(__file__).resolve().parent.parent / "assets" / "ninja_adventure"

# The cast, in atlas order. The order is historical (player, quest NPCs 1..12,
# named side folk, then three spares); who actually *wears* each sprite is
# decided in code — the char-select roster in src/gfx/atlas.rs and npc_sprite
# in src/gfx/scene.rs — so trust the per-line notes, not the position. Each
# Ninja Adventure strip holds one 16x16 frame per facing, in the order down,
# up, left, right — which is also the order the cells are baked in.
CAST = [
    ("BOY", "Boy"),  # char-select: "the young traveller"
    ("MASTER", "Master"),  # 1 Elder Rowan
    ("OLDMAN2", "OldMan2"),  # 2 Baker Poppy (the beret! the stripes!)
    ("VILLAGER_M", "Villager"),  # 3 Well-keeper Bram
    ("CHILD", "Child"),  # char-select: "the curious sprout"
    ("CAVEGIRL", "Cavegirl"),  # 5 Forager Maren (leaves in her hair)
    ("MANGREEN", "ManGreen"),  # char-select: "the greenwood ranger"
    ("VILLAGER2", "Villager2"),  # 7 Ferryman Wick
    ("EGGBOY", "EggBoy"),  # 8 Fisher Juniper (bucket hat)
    ("MONK", "Monk"),  # 9 Hermit Morrow
    ("INSPECTOR", "Inspector"),  # 10 Archivist Elm (spectacles)
    ("STATUE", "Statue"),  # 11 The Stone Golem
    ("OLDMAN3", "OldMan3"),  # 12 Sage Alderly
    ("OLDWOMAN", "OldWoman"),  # Granny Sorrel
    ("GREENMAN", "Greenman"),  # Old Nettle
    ("HUNTER", "Hunter"),  # Carpenter Alder
    ("WOMAN", "Woman"),  # char-select: "the roaming herbalist"
    ("NOBLE", "Noble"),  # Under-librarian Twill
    # The three NPCs whose sprites the char-select roster took over now wear
    # these spare villager looks (see npc_sprite in src/gfx/scene.rs).
    ("VILLAGER3", "Villager3"),  # Shepherd Ambrose
    ("VILLAGER4", "Villager4"),  # Wren
    ("PRINCESS", "Princess"),  # Hen-keeper Tilly
]


def na_tile(sheet_name, c, r):
    """One 16x16 cell from a Ninja Adventure tileset (margin-free grid)."""
    sheet = Image.open(NA_DIR / "tilesets" / f"{sheet_name}.png").convert("RGBA")
    return sheet.crop((c * TILE, r * TILE, c * TILE + TILE, r * TILE + TILE))


def na_idles(folder):
    """The four 16x16 idle frames (down, up, left, right) of a cast member.

    Most characters ship an `Idle.png` strip; a couple only have the compact
    `SpriteSheet.png`, whose top row is the same four facings.
    """
    idle = NA_DIR / folder / "Idle.png"
    sheet = Image.open(idle if idle.exists() else NA_DIR / folder / "SpriteSheet.png")
    sheet = sheet.convert("RGBA")
    return [sheet.crop((d * TILE, 0, d * TILE + TILE, TILE)) for d in range(4)]


def na_walks(folder):
    """Two stride frames per facing (down, up, left, right) from Walk.png,
    where columns are facings and rows are the four walk-cycle frames."""
    sheet = Image.open(NA_DIR / folder / "Walk.png").convert("RGBA")
    frames = []
    for d in range(4):
        for row in (1, 3):  # the two full-stride frames of the 4-frame cycle
            frames.append(
                sheet.crop((d * TILE, row * TILE, d * TILE + TILE, row * TILE + TILE))
            )
    return frames


def cell(sheet, c, r):
    """Cut one 16x16 tile from a Kenney sheet (1px margins)."""
    x, y = c * 17, r * 17
    return sheet.crop((x, y, x + TILE, y + TILE))


def over(base, top):
    out = base.copy()
    out.alpha_composite(top)
    return out


def tint(sprite, rgb):
    """Recolor a sprite by luminance to give each NPC their own tunic color."""
    out = Image.new("RGBA", sprite.size, (0, 0, 0, 0))
    for xy in [(x, y) for y in range(sprite.height) for x in range(sprite.width)]:
        r, g, b, a = sprite.getpixel(xy)
        if a == 0:
            continue
        lum = (0.3 * r + 0.6 * g + 0.1 * b) / 200.0
        out.putpixel(
            xy,
            (
                min(255, int(rgb[0] * lum)),
                min(255, int(rgb[1] * lum)),
                min(255, int(rgb[2] * lum)),
                a,
            ),
        )
    return out


def from_art(art, palette):
    """A 16x16 sprite from 16 rows of 16 palette characters ('.' = clear)."""
    rows = [line for line in art.strip("\n").split("\n")]
    img = Image.new("RGBA", (TILE, TILE), (0, 0, 0, 0))
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch != ".":
                img.putpixel((x, y), palette[ch])
    return img


CHICKEN = """
................
................
................
......ww........
.....wwww.......
.....owyy.......
......ww........
....wwwww.......
...wwwwwww......
...wwwwwww......
...wwwwwww......
....wwwww.......
.....www........
......y.y.......
.....y..y.......
................
"""

SHEEP = """
................
................
................
...wwwwwwww.....
..wwwwwwwwww....
.wwwwwwwwwwww...
.wwwwwwwwwwkk...
.wwwwwwwwwkkkk..
.wwwwwwwwwkkkk..
.wwwwwwwwwwkk...
..wwwwwwwwww....
...wwwwwww......
....k...k.......
....k...k.......
................
................
"""

FROG = """
................
................
................
................
................
....gg...gg.....
....ggggggg.....
...ggkggkgg.....
...ggggggggg....
..ggggggggggg...
..gGGGGGGGGgg...
..ggggggggggg...
...gg.....gg....
..gg.......gg...
................
................
"""

MOTH = """
................
................
................
................
....m.....m.....
...mmm...mmm....
..mmmmm.mmmmm...
..mmmmmammmmm...
..mmmmaaammmm...
...mmmaaammm....
....mmaaamm.....
......aaa.......
......a.a.......
................
................
................
"""

STUMP = """
................
................
................
................
................
................
....LLLLLL......
...LLbbbbLL.....
...LbLLLLbL.....
...bbbbbbbb.....
...bbbbbbbb.....
...bbbbbbbb.....
..bbbbbbbbbb....
................
................
................
"""

BUTTERFLY_A = """
................
................
................
................
................
....pp....pp....
...pppp..pppp...
...ppppkkpppp...
....pppkkppp....
.....pp..pp.....
................
................
................
................
................
................
"""

BUTTERFLY_B = """
................
................
................
................
................
......p..p......
.....pp..pp.....
.....ppkkpp.....
......pkkp......
................
................
................
................
................
................
................
"""

BIRD_A = """
................
................
................
................
................
................
...k......k.....
..kkk....kkk....
....kkkkkk......
......kk........
................
................
................
................
................
................
"""

BIRD_B = """
................
................
................
................
................
................
................
................
..kkkkkkkkkk....
....kk..kk......
................
................
................
................
................
................
................
"""

FERRIS = """
................
................
...oo......oo...
..o.oo....oo.o..
..oo........oo..
....oooooooo....
...oooooooooo...
..oooooooooooo..
..ooko.oo.okoo..
..oooooooooooo..
..oooooooooooo..
...oooooooooo...
...o.o.o..o.o...
..o..o.o..o..o..
................
................
"""

CAT = """
................
................
................
....t...t.......
....tt.tt.......
....ttttt.......
....tktkt.......
....ttttt.......
....twwtt.tt....
...ttwwttttt....
...tttttttt.....
...tttttttt.....
....tt..tt......
................
................
................
"""

BOOKSHELF = """
LLLLLLLLLLLLLLLL
LbbbbbbbbbbbbbbL
Lb1e21g3e12g3ebL
Lb1e21g3e12g3ebL
Lb1e21g3e12g3ebL
LbbbbbbbbbbbbbbL
Lbg31e2g13ge21bL
Lbg31e2g13ge21bL
Lbg31e2g13ge21bL
LbbbbbbbbbbbbbbL
Lb2ge13g21e3g1bL
Lb2ge13g21e3g1bL
Lb2ge13g21e3g1bL
LbbbbbbbbbbbbbbL
LLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLL
"""

CHEST = """
................
................
................
....LLLLLLLL....
...LbbbbbbbbL...
...LbbbbbbbbL...
...LLLLLLLLLL...
...LbbbyybbbL...
...Lbbbyy1bbL...
...LbbbbbbbbL...
...LbbbbbbbbL...
...LLLLLLLLLL...
....k......k....
................
................
................
"""

RUNESTONE = """
................
................
................
......SS........
.....sssS.......
....sssssS......
....sscssS......
...ssscsssS.....
...sscscssS.....
...ssscsssS.....
...sssscssS.....
..ssssscsssS....
..sssssssssS....
..sSSSSSSSSS....
................
................
"""

HERB = """
................
................
................
................
................
......G..w......
....G.g.wGw..G..
...GgGg..w..gG..
....ggGg...Gg...
..G..gGg..gg....
...gg.gg.gG.....
.....g.ggg......
......ggg.......
.......g........
................
................
"""

WINDOW = """
bbbbbbbbbbbbbbbb
biiiiiiibiiiiiib
biiiiiiibiiiiiib
biiiiiiibiiiiiib
biiiiiiibiiiiiib
bbbbbbbbbbbbbbbb
bjjjjjjjbjjjjjjb
bjjjjjjjbjjjjjjb
bjjjjjjjbjjjjjjb
bjjjjjjjbjjjjjjb
biiiiiiibiiiiiib
bbbbbbbbbbbbbbbb
................
................
................
................
"""

PAINTING = """
................
.LLLLLLLLLLLLLL.
.LyLLLLLLLLLLyL.
.L2222222222y2L.
.L22222y222222L.
.L222222222222L.
.Lg2222222g2ggL.
.Lggg3ggg3gggL..
.Lg3gg3gg3gg3L..
.LgggggggggggL..
.LyLLLLLLLLLLyL.
.LLLLLLLLLLLLLL.
................
................
................
................
"""

PLANT = """
................
......G.G.......
.....GgGgG......
....Gg3g3gG.....
...Gg3gGg3gG....
....Gg3g3gG.....
.....GgGgG......
.......g........
.......g........
......ooo.......
.....ooooo......
.....obbbo......
.....ooooo......
......ooo.......
................
................
"""

PEDESTAL = """
................
.......c........
......ccc.......
......ccc.......
.....ccccc......
......ccc.......
.......c........
.....ssssss.....
....ssSSSSss....
....sSSSSSSs....
....sSSSSSSs....
...ssssssssss...
...sSSSSSSSSs...
..ssssssssssss..
..sSSSSSSSSSSs..
................
"""

VOID = """
vvvvvvvvvvvvvvvv
vvvvvvvvvvvvvvvv
vvvvvVvvvvvvvvvv
vvvvvvvvvvvvvvvv
vvvvvvvvvvvvVvvv
vvvvvvvvvvvvvvvv
vvVvvvvvvvvvvvvv
vvvvvvvvvvvvvvvv
vvvvvvvvvVvvvvvv
vvvvvvvvvvvvvvvv
vvvvVvvvvvvvvvvv
vvvvvvvvvvvvvvvv
vvvvvvvvvvvvvVvv
vvvvvvvvvvvvvvvv
vvvvvvvVvvvvvvvv
vvvvvvvvvvvvvvvv
"""

PALETTE = {
    "w": (240, 238, 230, 255),
    "o": (222, 120, 80, 255),
    "y": (240, 200, 60, 255),
    "k": (40, 36, 40, 255),
    "g": (110, 185, 90, 255),
    "G": (200, 230, 170, 255),
    "m": (214, 208, 232, 255),
    "a": (150, 140, 170, 255),
    "p": (232, 168, 200, 255),
    "L": (214, 188, 148, 255),
    "b": (124, 94, 62, 255),
    "t": (214, 164, 110, 255),
    "1": (188, 92, 84, 255),
    "2": (108, 140, 178, 255),
    "3": (128, 166, 106, 255),
    "e": (222, 198, 152, 255),
    "v": (18, 16, 22, 255),
    "V": (26, 23, 32, 255),
    "s": (152, 152, 164, 255),
    "S": (104, 104, 118, 255),
    "c": (122, 208, 222, 255),
    "i": (200, 224, 244, 255),
    "j": (150, 188, 222, 255),
}

# NPC tunic colors, in quest order 1..12 (canonical here; tints the sprites).
NPC_COLORS = [
    (216, 186, 130),
    (234, 156, 146),
    (150, 184, 214),
    (152, 214, 122),
    (206, 130, 170),
    (196, 186, 156),
    (126, 168, 190),
    (142, 196, 196),
    (176, 156, 208),
    (188, 176, 146),
    (168, 168, 180),
    (226, 204, 152),
]
# Body/hair variety per NPC: (body col, body row, hair col, hair row) on the
# characters sheet. Bodies live at cols 0-1; hair/hats at cols 19-22 & 28-31.
# Flavor villagers who live inside the enterable houses: same recipe as the
# quest NPCs, their own colors and hair so nobody looks like anyone's twin.
VILLAGER_COLORS = [(188, 168, 138), (170, 190, 160), (208, 178, 188)]
VILLAGER_LOOKS = [(1, 3, 22, 0), (0, 2, 29, 0), (1, 1, 30, 0)]

NPC_LOOKS = [
    (0, 0, 20, 0),
    (1, 0, 21, 8),
    (0, 1, 28, 0),
    (1, 1, 20, 5),
    (0, 2, 21, 9),
    (1, 2, 28, 1),
    (0, 0, 21, 5),
    (1, 1, 20, 8),
    (0, 2, 28, 5),
    (1, 0, 20, 9),
    (0, 3, None, None),  # the golem gets the sturdy frame, no hat
    (0, 1, 21, 0),
]


def main(sheet_path, chars_path):
    sheet = Image.open(sheet_path).convert("RGBA")
    chars = Image.open(chars_path).convert("RGBA")

    shirt = cell(chars, 10, 0)  # plain tunic, used as the tint base

    def npc(i):
        bc, br, hc, hr = NPC_LOOKS[i]
        body = cell(chars, bc, br)
        spr = over(body, tint(shirt, NPC_COLORS[i]))
        if i == 10:  # golem: tint the whole body stony grey
            spr = tint(body, (168, 168, 180))
        elif hc is not None:
            spr = over(spr, cell(chars, hc, hr))
        return spr

    def villager(i):
        bc, br, hc, hr = VILLAGER_LOOKS[i]
        spr = over(cell(chars, bc, br), tint(shirt, VILLAGER_COLORS[i]))
        return over(spr, cell(chars, hc, hr))

    player = over(over(cell(chars, 0, 0), cell(chars, 10, 0)), cell(chars, 20, 0))

    cells = [
        # terrain bases (opaque)
        ("GRASS", cell(sheet, 5, 0)),
        ("GRASS_ALT", cell(sheet, 5, 1)),
        ("PATH", cell(sheet, 6, 0)),
        ("PATH_ALT", cell(sheet, 6, 1)),
        ("SAND", cell(sheet, 8, 0)),
        ("WATER_A", cell(sheet, 0, 0)),
        ("WATER_B", cell(sheet, 1, 0)),
        ("FLOOR", cell(sheet, 34, 15)),
        ("STONE", cell(sheet, 4, 26)),
        ("FLOWER_ORANGE", over(cell(sheet, 5, 0), cell(sheet, 29, 9))),
        ("FLOWER_WHITE", over(cell(sheet, 5, 0), cell(sheet, 31, 9))),
        ("FLOWER_BLUE", over(cell(sheet, 5, 0), cell(sheet, 30, 9))),
        # overlays (transparent, drawn on a base)
        ("TREE_GREEN", cell(sheet, 13, 9)),
        ("TREE_ORANGE", cell(sheet, 14, 9)),
        ("PINE", cell(sheet, 16, 9)),
        ("BUSH", cell(sheet, 25, 9)),
        ("BERRY_BUSH", cell(sheet, 24, 9)),
        ("SPROUT", cell(sheet, 22, 10)),
        ("SPROUT_ALT", cell(sheet, 22, 11)),
        ("LILY", cell(sheet, 25, 11)),
        ("ROCK_GREY", cell(sheet, 54, 21)),
        ("ROCK_BROWN", cell(sheet, 54, 19)),
        ("FENCE", cell(sheet, 52, 23)),
        ("GATE", cell(sheet, 46, 23)),
        ("SIGN", cell(sheet, 19, 0)),
        ("DOOR", cell(sheet, 28, 5)),
        ("BRIDGE", cell(sheet, 34, 17)),
        ("WALL", cell(sheet, 9, 2)),
        ("ROOF", cell(sheet, 25, 22)),
        ("CAMPFIRE_A", cell(sheet, 14, 8)),
        ("CAMPFIRE_B", cell(sheet, 15, 8)),
        ("TORCH_UNLIT", cell(sheet, 16, 7)),
        ("TORCH_LIT_A", cell(sheet, 17, 7)),
        ("TORCH_LIT_B", cell(sheet, 17, 8)),
        # people & friends
        ("PLAYER", player),
        *[(f"NPC_{i + 1}", npc(i)) for i in range(12)],
        ("CHICKEN", from_art(CHICKEN, PALETTE)),
        ("SHEEP", from_art(SHEEP, PALETTE)),
        ("FROG", from_art(FROG, PALETTE)),
        ("MOTH", from_art(MOTH, PALETTE)),
        ("FERRIS", from_art(FERRIS, PALETTE)),
        # grass decor & ambient life
        ("MUSHROOM", cell(sheet, 48, 4)),
        ("MUSHROOM_TALL", cell(sheet, 48, 3)),
        ("STUMP", from_art(STUMP, PALETTE)),
        ("PEBBLE", cell(sheet, 56, 20)),
        ("FLOWER_SMALL_A", cell(sheet, 28, 9)),
        ("FLOWER_SMALL_B", cell(sheet, 31, 9)),
        ("BUTTERFLY_A", from_art(BUTTERFLY_A, PALETTE)),
        ("BUTTERFLY_B", from_art(BUTTERFLY_B, PALETTE)),
        ("BIRD_A", from_art(BIRD_A, PALETTE)),
        ("BIRD_B", from_art(BIRD_B, PALETTE)),
        # indoors: furniture overlays for the enterable houses
        ("VOID", from_art(VOID, PALETTE)),
        ("RUG", cell(sheet, 27, 25)),
        ("TABLE", cell(sheet, 26, 4)),
        ("STOOL", cell(sheet, 19, 5)),
        ("BED_HEAD", cell(sheet, 14, 1)),
        ("BED_FOOT", cell(sheet, 14, 3)),
        ("HEARTH_A", cell(sheet, 13, 0)),
        ("HEARTH_B", cell(sheet, 14, 0)),
        ("BARREL", cell(sheet, 22, 0)),
        ("CRATE", cell(sheet, 26, 0)),
        ("SHELF", cell(sheet, 31, 0)),
        ("BOOKSHELF", from_art(BOOKSHELF, PALETTE)),
        ("CAT", from_art(CAT, PALETTE)),
        *[(f"VILLAGER_{i + 1}", villager(i)) for i in range(3)],
        # side content: the cellar chest, hidden runestones, moon-mint
        ("CHEST", from_art(CHEST, PALETTE)),
        ("RUNESTONE", from_art(RUNESTONE, PALETTE)),
        ("HERB", from_art(HERB, PALETTE)),
        # ── the variety pass: more of the sheet, so the world isn't monotone ──
        # richer ground bases (opaque)
        ("GRASS_MOTTLED", cell(sheet, 3, 16)),
        ("AUTUMN_GRASS", cell(sheet, 3, 19)),
        ("BLOSSOM_GRASS", cell(sheet, 3, 22)),
        ("FLOWERBED_RED", cell(sheet, 3, 7)),
        ("FLOWERBED_WHITE", cell(sheet, 3, 10)),
        ("FLOWERBED_BLUE", cell(sheet, 3, 13)),
        ("COBBLE", cell(sheet, 6, 2)),
        ("COBBLE_ALT", cell(sheet, 6, 3)),
        # more trees & bushes (overlays)
        ("TREE_TEAL", cell(sheet, 15, 9)),
        ("PINE_ORANGE", cell(sheet, 17, 9)),
        ("PINE_TEAL", cell(sheet, 18, 9)),
        ("DEAD_TREE", cell(sheet, 27, 11)),
        ("BUSH_FLOWER", cell(sheet, 25, 10)),
        ("BUSH_FRUIT", cell(sheet, 26, 10)),
        ("HEDGE", cell(sheet, 19, 9)),
        # the rock family (overlays)
        ("ROCK_BROWN_B", cell(sheet, 55, 19)),
        ("ROCK_BROWN_C", cell(sheet, 56, 19)),
        ("ROCK_GREY_B", cell(sheet, 55, 21)),
        ("ROCK_GREY_C", cell(sheet, 56, 21)),
        ("ROCK_MOSSY_BROWN", cell(sheet, 55, 20)),
        ("ROCK_MOSSY_GREY", cell(sheet, 55, 22)),
        ("CRACK_A", cell(sheet, 26, 19)),
        ("CRACK_B", cell(sheet, 26, 20)),
        # riverbank & village life (overlays)
        ("LILY_PAD", cell(sheet, 26, 11)),
        ("SHRUB_SMALL", cell(sheet, 28, 11)),
        ("STUMP_OLD", cell(sheet, 53, 19)),
        ("STALL_A", cell(sheet, 15, 6)),
        ("STALL_B", cell(sheet, 16, 6)),
        ("AWNING_ORANGE", cell(sheet, 10, 0)),
        ("AWNING_GREEN", cell(sheet, 11, 0)),
        ("IVY", cell(sheet, 44, 23)),
        # ── the animated cast (Ninja Adventure pack, see assets/CREDITS.md) ──
        # Four idle cells per member (facing down, up, left, right); only the
        # first of each quartet gets a named constant.
        *[
            (f"CAST_{name}" if d == 0 else None, frame)
            for name, folder in CAST
            for d, frame in enumerate(na_idles(folder))
        ],
        # The player's stride: two frames per facing, same facing order.
        *[
            ("PLAYER_WALK" if i == 0 else None, frame)
            for i, frame in enumerate(na_walks("Boy"))
        ],
        # ── biome grounds & props (Ninja Adventure tilesets) ─────────────────
        # Each overworld zone gets its own ground family: plain + two
        # tuft-decorated variants, all seamless fills.
        ("MARSH", na_tile("TilesetFloor", 0, 12)),
        ("MARSH_B", na_tile("TilesetFloor", 1, 12)),
        ("MARSH_C", na_tile("TilesetFloor", 3, 12)),
        ("DEEP", na_tile("TilesetFloor", 11, 12)),
        ("DEEP_B", na_tile("TilesetFloor", 12, 12)),
        ("DEEP_C", na_tile("TilesetFloor", 14, 12)),
        ("SNOW", na_tile("TilesetFloor", 0, 19)),
        ("SNOW_B", na_tile("TilesetFloor", 1, 19)),
        ("SNOW_C", na_tile("TilesetFloor", 3, 19)),
        # swaying tall-grass pairs, one per biome
        ("TUFT_DEEP_A", na_tile("TilesetFloorDetail", 0, 2)),
        ("TUFT_DEEP_B", na_tile("TilesetFloorDetail", 1, 2)),
        ("TUFT_MARSH_A", na_tile("TilesetFloorDetail", 6, 2)),
        ("TUFT_MARSH_B", na_tile("TilesetFloorDetail", 7, 2)),
        ("TUFT_SNOW_A", na_tile("TilesetFloorDetail", 0, 3)),
        ("TUFT_SNOW_B", na_tile("TilesetFloorDetail", 1, 3)),
        # ground-litter details
        ("LEAF_LITTER", na_tile("TilesetFloorDetail", 1, 0)),
        ("GOLD_SPECKS", na_tile("TilesetFloorDetail", 3, 0)),
        ("TWIG", na_tile("TilesetFloorDetail", 7, 0)),
        ("BONE", na_tile("TilesetFloorDetail", 14, 0)),
        # snowbound props
        ("SNOWROCK_A", na_tile("TilesetNature", 4, 12)),
        ("SNOWROCK_B", na_tile("TilesetNature", 6, 12)),
        ("ICE_A", na_tile("TilesetNature", 8, 13)),
        ("ICE_B", na_tile("TilesetNature", 9, 13)),
        # forest & marsh props
        ("NA_STONE", na_tile("TilesetNature", 17, 9)),
        ("LOG_NA", na_tile("TilesetNature", 12, 13)),
        ("FERN", na_tile("TilesetNature", 4, 11)),
        ("BOGBERRY", na_tile("TilesetNature", 4, 14)),
        # village garden flowers
        ("SUNFLOWER", na_tile("TilesetNature", 0, 11)),
        ("TULIP", na_tile("TilesetNature", 3, 11)),
        # fence pieces for the edge-aware pass: the vertical run is the
        # horizontal rail turned on its side, so the wood always matches
        ("FENCE_V", cell(sheet, 52, 23).transpose(Image.ROTATE_90)),
        ("FENCE_POST", cell(sheet, 45, 23)),
        # single flowers as transparent overlays, so they bloom on any ground
        ("FLOWER_O_OVER", cell(sheet, 29, 9)),
        ("FLOWER_W_OVER", cell(sheet, 31, 9)),
        ("FLOWER_B_OVER", cell(sheet, 30, 9)),
        # ── the Great Library showcase: windows, art, and exhibits ───────────
        ("WINDOW", from_art(WINDOW, PALETTE)),
        ("PAINTING", from_art(PAINTING, PALETTE)),
        ("PLANT", from_art(PLANT, PALETTE)),
        ("PEDESTAL", from_art(PEDESTAL, PALETTE)),
    ]

    rows = (len(cells) + COLS - 1) // COLS
    atlas = Image.new("RGBA", (COLS * TILE, rows * TILE), (0, 0, 0, 0))
    for i, (_, img) in enumerate(cells):
        atlas.paste(img, ((i % COLS) * TILE, (i // COLS) * TILE))
    atlas.save("assets/atlas.png")

    print(f"atlas: {atlas.width}x{atlas.height}, {len(cells)} cells")
    for i, (name, _) in enumerate(cells):
        if name is not None:
            print(f"pub const {name}: u16 = {i};")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
